name: Terraform CI/CD

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.12.2

jobs:
  terraform:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      ##################################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      ##################################################

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      ##################################################

      - name: Terraform Version
        run: terraform version

      ##################################################

      - name: Terraform Format
        run: terraform fmt -recursive

      ##################################################

      - name: Debug Terraform Files
        run: |
         echo "Current directory:"
         pwd

         echo "Repository files:"
         find . -maxdepth 4 -type f | sort

         echo "Backend config:"
         cat env/dev/backend.hcl

         echo "Terraform backend declarations:"
         grep -R 'backend "s3"' -n . || true

      - name: Terraform Init
        run: |
         terraform init \
          -input=false \
          -reconfigure \
          -backend-config="env/dev/backend.hcl"

      ##################################################

      - name: Terraform Validate
        run: terraform validate

      ##################################################

      - name: Terraform Plan
        run: |
         terraform plan \
          -input=false \
          -var-file="env/dev/terraform.tfvars" \
          -out=tfplan

      ##################################################

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      ##################################################

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
