name: EKS-CLUSTER

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.12.2"
  AWS_REGION: us-east-1
  TF_WORKING_DIR: eks/

jobs:

#########################################################
# Phase 1 - Core Infrastructure
#########################################################

  infrastructure-phase1:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -diff
        continue-on-error: false

      - name: Terraform Validate
        run: terraform validate
        continue-on-error: false

      - name: Terraform plan
        run: |
          terraform plan -var-file=dev.tfvars -input=false
        continue-on-error: false
