name: EKS-CLUSTER

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-eks
  cancel-in-progress: false

env:
  TF_VERSION: "1.12.2"
  AWS_REGION: us-east-1
  TF_WORKING_DIR: eks/

jobs:
  infrastructure-phase1:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407933037859:role/terraform-rola
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -input=false
      - run: terraform force-unlock -force 17428651-9558-2924-8133-484050042357

      - name: Terraform Format Check
        run: terraform fmt -check -diff

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file=dev.tfvars \
            -out=tfplan \
            -input=false

      - name: Terraform Apply
        run: |
          terraform apply \
            -auto-approve \
            -input=false \
            tfplan
